import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import AuthProvider from "@/providers/AuthProvider";
import { Query } from "@tanstack/react-query";
import QueryProvider from "@/providers/QueryProvider";
import { UserProvider } from "@/providers/UserProvider";
import { FoodProvider } from "@/providers/FoodProvider";
import { CategoriesProvider } from "@/providers/CategoriesProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#404040]`}
      >
        <QueryProvider>
          <AuthProvider>
            <UserProvider>
              <FoodProvider>
                <CategoriesProvider>
                  <Header />
                  {children}
                  <Footer />
                </CategoriesProvider>
              </FoodProvider>
            </UserProvider>
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
